# Generated by Django 4.0.3 on 2022-04-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='movieList',
        ),
        migrations.AddField(
            model_name='profile',
            name='movieList',
            field=models.ManyToManyField(related_name='profile_movielist', to='movies.movielist'),
        ),
    ]
