# Generated by Django 4.0.3 on 2022-04-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_profile_movielist_profile_movielist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Collection',
        ),
    ]
