# Generated by Django 4.0.3 on 2022-04-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_profile_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
