# Generated by Django 4.0.3 on 2022-04-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Movie',
        ),
    ]
