# Generated by Django 4.0.3 on 2022-04-02 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_rename_collection_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieList',
            field=models.ManyToManyField(to='movies.movielist'),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
